/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const modalOverlay: string;
const modalBody: string;
const modalContent: string;
const modalClose: string;
const modalButtonsContainer: string;
const modalButton: string;

export {
	modalOverlay as "modal-overlay",
	modalOverlay,
	modalBody as "modal-body",
	modalBody,
	modalContent as "modal-content",
	modalContent,
	modalClose as "modal-close",
	modalClose,
	modalButtonsContainer as "modal-buttons-container",
	modalButtonsContainer,
	modalButton as "modal-button",
	modalButton
};

export default {
	"modal-overlay": modalOverlay,
	modalOverlay,
	"modal-body": modalBody,
	modalBody,
	"modal-content": modalContent,
	modalContent,
	"modal-close": modalClose,
	modalClose,
	"modal-buttons-container": modalButtonsContainer,
	modalButtonsContainer,
	"modal-button": modalButton,
	modalButton
};
