/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const choicesList: string;
const choicesItem: string;
const choiceItemBody: string;
const btnAdd: string;

export {
	choicesList as "choices-list",
	choicesList,
	choicesItem as "choices-item",
	choicesItem,
	choiceItemBody as "choice-item-body",
	choiceItemBody,
	btnAdd as "btn-add",
	btnAdd
};

export default {
	"choices-list": choicesList,
	choicesList,
	"choices-item": choicesItem,
	choicesItem,
	"choice-item-body": choiceItemBody,
	choiceItemBody,
	"btn-add": btnAdd,
	btnAdd
};
