/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const modal: string;
const modalContent: string;
const sceneEditor: string;
const choicesEditor: string;

export {
	modal,
	modalContent as "modal-content",
	modalContent,
	sceneEditor as "scene-editor",
	sceneEditor,
	choicesEditor as "choices-editor",
	choicesEditor
};

export default {
	modal,
	"modal-content": modalContent,
	modalContent,
	"scene-editor": sceneEditor,
	sceneEditor,
	"choices-editor": choicesEditor,
	choicesEditor
};
