/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const header: string;
const viewer: string;
const controls: string;
const editor: string;
const editorActive: string;
const editorInactive: string;
const btnEdit: string;
const btnDelete: string;

export {
	container,
	header,
	viewer,
	controls,
	editor,
	editorActive as "editor-active",
	editorActive,
	editorInactive as "editor-inactive",
	editorInactive,
	btnEdit as "btn-edit",
	btnEdit,
	btnDelete as "btn-delete",
	btnDelete
};

export default {
	container,
	header,
	viewer,
	controls,
	editor,
	"editor-active": editorActive,
	editorActive,
	"editor-inactive": editorInactive,
	editorInactive,
	"btn-edit": btnEdit,
	btnEdit,
	"btn-delete": btnDelete,
	btnDelete
};
