/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const choiceEditor: string;
const choiceEditorFooter: string;

export {
	choiceEditor as "choice-editor",
	choiceEditor,
	choiceEditorFooter as "choice-editor-footer",
	choiceEditorFooter
};

export default {
	"choice-editor": choiceEditor,
	choiceEditor,
	"choice-editor-footer": choiceEditorFooter,
	choiceEditorFooter
};
